/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Gabriel1
 */
public class TelaOrcamento extends javax.swing.JDialog {

    /**
     * Creates new form Orcamento
     */
    public TelaOrcamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            String data = formatter.format(new Date());
            txtData.setText(data);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOrcamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQtdProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblTotalProduto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        cbServico = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtQtdServico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtValorServico = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServico = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        lblTotalServico = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAprovado = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lblTotalOrcamento = new javax.swing.JLabel();
        btnAddProduto = new javax.swing.JButton();
        btnRemoveProduto = new javax.swing.JButton();
        btnAddServico = new javax.swing.JButton();
        btnRemoveServico = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtDescontoServico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDescontoProduto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDescontoOrcamento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnPesquisaCliente = new javax.swing.JButton();
        txtPesquisaOrcamento = new javax.swing.JButton();
        btnPesquisaProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Orçamento - Agenda Financeira");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 48, -1, -1));

        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 45, 470, -1));

        jLabel2.setText("Orçamento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        txtOrcamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, -1));

        jLabel3.setText("Data:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 17, -1, -1));

        txtData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 80, -1));

        jLabel4.setText("Produto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 83, -1, -1));

        txtProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 80, 190, -1));

        jLabel5.setText("Cd. Produto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 79, -1, -1));

        txtCodProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 80, -1));

        jLabel6.setText("Qtd:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 88, -1, -1));

        txtQtdProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtQtdProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 85, 50, -1));

        jLabel7.setText("Valor R$");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 114, -1, -1));

        txtValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 111, 86, -1));

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cd Produto", "Produto", "Qtd", "R$ Unit.", "R$ Total"
            }
        ));
        jScrollPane1.setViewportView(tblProduto);
        if (tblProduto.getColumnModel().getColumnCount() > 0) {
            tblProduto.getColumnModel().getColumn(0).setResizable(false);
            tblProduto.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblProduto.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblProduto.getColumnModel().getColumn(2).setResizable(false);
            tblProduto.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblProduto.getColumnModel().getColumn(3).setResizable(false);
            tblProduto.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblProduto.getColumnModel().getColumn(4).setPreferredWidth(60);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, 610, 100));

        jLabel9.setText("Total R$");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 245, -1, -1));

        lblTotalProduto.setText("0,00");
        jPanel1.add(lblTotalProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 245, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 265, 610, 10));

        jLabel11.setText("Serviço:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 289, -1, -1));

        cbServico.setEditable(true);
        cbServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 286, 186, -1));

        jLabel12.setText("Qtd:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 289, -1, -1));

        txtQtdServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtQtdServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 286, 42, -1));

        jLabel13.setText("Valor R$");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        txtValorServico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 1, true));
        jPanel1.add(txtValorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 86, -1));

        tblServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serviço", "Qtd", "R$ Unit.", "R$ Total"
            }
        ));
        jScrollPane2.setViewportView(tblServico);
        if (tblServico.getColumnModel().getColumnCount() > 0) {
            tblServico.getColumnModel().getColumn(0).setPreferredWidth(300);
            tblServico.getColumnModel().getColumn(1).setResizable(false);
            tblServico.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblServico.getColumnModel().getColumn(2).setResizable(false);
            tblServico.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblServico.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 364, 610, 100));

        jLabel15.setText("Total R$");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 474, -1, -1));

        lblTotalServico.setText("0,00");
        jPanel1.add(lblTotalServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 474, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 494, 610, 10));

        btnAprovado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Good mark.png"))); // NOI18N
        btnAprovado.setText("Aprovado");
        jPanel1.add(btnAprovado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 574, -1, -1));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Modify.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        jPanel1.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 574, -1, -1));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 574, -1, -1));

        jLabel17.setText("Total Orçamento R$");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 524, -1, -1));

        lblTotalOrcamento.setText("0,00");
        jPanel1.add(lblTotalOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 524, -1, -1));

        btnAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Create.png"))); // NOI18N
        jPanel1.add(btnAddProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 111, -1, -1));

        btnRemoveProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/No-entry.png"))); // NOI18N
        jPanel1.add(btnRemoveProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 111, -1, -1));

        btnAddServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Create.png"))); // NOI18N
        jPanel1.add(btnAddServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 334, -1, -1));

        btnRemoveServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/No-entry.png"))); // NOI18N
        jPanel1.add(btnRemoveServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 334, -1, -1));

        jLabel19.setText("Desconto:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 289, -1, -1));

        txtDescontoServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtDescontoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 77, -1));

        jLabel20.setText("Desconto:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, -1, -1));

        txtDescontoProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtDescontoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, -1));

        jLabel21.setText("Desconto:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 524, -1, -1));

        txtDescontoOrcamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jPanel1.add(txtDescontoOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 524, 77, -1));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 574, -1, -1));

        btnPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.png"))); // NOI18N
        jPanel1.add(btnPesquisaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 45, -1, -1));

        txtPesquisaOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.png"))); // NOI18N
        jPanel1.add(txtPesquisaOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 13, -1, -1));

        btnPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.png"))); // NOI18N
        jPanel1.add(btnPesquisaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaOrcamento dialog = new TelaOrcamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAddServico;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAprovado;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaProduto;
    private javax.swing.JButton btnRemoveProduto;
    private javax.swing.JButton btnRemoveServico;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTotalOrcamento;
    private javax.swing.JLabel lblTotalProduto;
    private javax.swing.JLabel lblTotalServico;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTable tblServico;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtDescontoOrcamento;
    private javax.swing.JTextField txtDescontoProduto;
    private javax.swing.JTextField txtDescontoServico;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtOrcamento;
    private javax.swing.JButton txtPesquisaOrcamento;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtdProduto;
    private javax.swing.JTextField txtQtdServico;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorServico;
    // End of variables declaration//GEN-END:variables
}
